version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
#      SPRING_PROFILES_ACTIVE: production
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: content_calendar
      PGUSER: postgres
      PGPASSWORD: password

  db:
    image: postgres:15-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: content_calendar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
